#!/bin/bash

STANDARD="Drupal,DrupalPractice"

echo "~ ~ RUNNING PRE-COMMIT HOOKS ~ ~"
echo "RUNNING COMPOSER VALIDATE"
composer validate

echo "If there are errors run this cmd - vendor/bin/phpcs --standard Drupal, DrupalPractice to relove them."

echo "RUNNING phpcs"
vendor/bin/phpcs --standard=$STANDARD src